More Jokes API
osdc/osdc-bot pull request #22
Opened 2016-10-02 19:07 UTC by Yash17Agrawal

Fixed issue regarding #1

2016-10-02 21:01 UTC, 526avijitgupta commented
@Yash17Agrawal There are merge conflicts that need to be resolved. Run the following commands:
```bash
git branch # Verify that the current branch is master
git remote add upstream https://github.com/osdc/osdc-bot
git fetch upstream
git merge upstream/develop
# Resolve merge conflicts if there are any
git add .
git commit -m "Update branch and resolve merge conflicts" # Or any other commit message
git push origin master
```

Please make sure to verify that the bot is functioning correctly before committing and pushing your code in the final step!

2016-10-03 06:55 UTC, Yash17Agrawal commented
@526avijitgupta  sir shouldnt it be git merge upstream/master ?

2016-10-03 08:04 UTC, yashmehrotra requested changes

2016-10-03 08:04 UTC, yashmehrotra commented on constants.js
> +const JOKES_API_URL =[ 'http://api.icndb.com/jokes/random','http://tambal.azurewebsites.net/joke/random'];
Fix Linting, also, convert this list into a list of Objects, where we can store url and method to access the joke.

2016-10-03 08:04 UTC, yashmehrotra commented on services/jokeService.js
> +    request(randomQuote, (error, response, body) => {
Change name to `randomJoke`

2016-10-03 08:04 UTC, yashmehrotra commented on services/jokeService.js
> +	if (index==0)
Same as the comment on `constants.js`, instead of `if/else` the access method should be there in `const JOKE_API_URL`

2016-10-03 11:52 UTC, Yash17Agrawal commented on services/jokeService.js
> +	if (index==0)
okay @yashmehrotra

2016-10-08 21:56 UTC, Yash17Agrawal commented
@526avijitgupta @yashmehrotra  Please review.

2016-10-08 21:58 UTC, yashmehrotra commented on constants.js
> +const JOKES_API_URL =[ 'http://api.icndb.com/jokes/random','http://tambal.azurewebsites.net/joke/random'];
@Yash17Agrawal convert this list into a list of Objects, where we can store url and method to access the joke.

2016-10-09 12:22 UTC, 526avijitgupta requested changes
@Yash17Agrawal Minor changes requested. Overall looks good!

2016-10-09 12:22 UTC, 526avijitgupta commented on services/jokeService.js
> +    const randomQuote =  constants.JOKES_API_URL[index];
There seems to be an extra space after `=`

2016-10-09 12:22 UTC, 526avijitgupta commented on services/jokeService.js
> +        }
Better to do:
```js
const jokeText = (
  (index === 0) ? JSON.parse(body).value.joke : JSON.parse(body).joke);
return callback(jokeText, username);
```

2016-10-09 13:34 UTC, 526avijitgupta approved these changes
LGTM! @yashmehrotra -- anything from your side ?

2016-10-09 15:34 UTC, yashmehrotra commented
@526avijitgupta Using `if (index == 0) {} else {}` is wrong, its better if we store the access method in the list, something like,
```
[
  {
     'url': 'http://abc.def',
     'joke_val': 'response.body.value.joke'
   },
    {
    }
]
```

2016-10-09 15:36 UTC, yashmehrotra commented
@526avijitgupta LGTM
@Yash17Agrawal Good work!

2016-10-09 15:37 UTC, merged